#!/bin/bash
# Description: Script to start build of the selected packages
# Author: Daniele Rondina, geaaru@funtoo.org

if [ -n "$DEBUG" ] ; then set -x ; fi

luet_dir=$(dirname ${BASH_SOURCE[0]}})/../luet
luet_values=${luet_dir}/luet-repo.values

ENABLE_DOCKER_HOST=${ENABLE_DOCKER_HOST:-true}
ENABLE_BUILDKIT=${ENABLE_BUILDKIT:-false}
PUSH_IMAGES=${PUSH_IMAGES:-false}
FIRE_TASK=${FIRE_TASK:-0}

main () {

  if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
    echo "Missng MOTTAINAI_CLI_PROFILE env variable"
    exit 1
  fi

  if [ -z "${NAMESPACE}" ] ; then
    echo "Missing NAMESPACE env variable."
    echo "Normally this variable is equal to repository name."
    exit 1
  fi

  if [ -z "${PACKAGES}" ] ; then
    echo "Missing PACKAGES env variable."
    echo "This variable contains the packages to build."
    exit 1
  fi

  isvalid=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | length")
  if [ "${isvalid}" == "0" ] ; then
    echo "Select repository not defined on luet-repo.values file."
    exit 1
  fi

  repo=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .http_repo" -r)
  repo_branch=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .branch" -r)
 
  mottainai-cli task compile ${luet_dir}/templates/build-pkgs.tmpl \
    -s namespace="${NAMESPACE}" \
    -s repo="${repo}" \
    -s branch="${repo_branch}" \
    -s enable_docker_host="${ENABLE_DOCKER_HOST}" \
    -s enable_buildkit="${ENABLE_BUILDKIT}" \
    -s push_images="${PUSH_IMAGES}" \
    -s pkgs="${PACKAGES}" \
    -o /tmp/build-pkgs.yaml || return 1

  if [ "${FIRE_TASK}" = "1" ] ; then
    mottainai-cli task create --yaml /tmp/build-pkgs.yaml || return 1
  fi

  return 0
}


main $@
exit $?

# vim: filetype=sh
