#!/bin/bash
# Description: Script to update/generate luet tasks and pipeline.
# Author: Daniele Rondina, geaaru@funtoo.org

if [ -n "$DEBUG" ] ; then set -x ; fi

luet_dir=$(dirname ${BASH_SOURCE[0]}})/../luet
luet_values=${luet_dir}/luet-repo.values

REPOS=$(yq r ${luet_values} 'values.repositories' -l)

if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
  echo "Missng MOTTAINAI_CLI_PROFILE env variable"
  exit 1
fi

for ((i=0;i<${REPOS};i++)) ; do

  name=$(yq r ${luet_values} "values.repositories[$i].name")
  branch=$(yq r ${luet_values} "values.repositories[$i].branch")
  http_repo=$(yq r ${luet_values} "values.repositories[$i].http_repo")
  ssh_repo=$(yq r ${luet_values} "values.repositories[$i].ssh_repo")
  upgrade_kit=$(yq r ${luet_values} "values.repositories[$i].upgrade_kit")

  echo "Create task for bump repo ${name}..."
  mottainai-cli task compile ${luet_dir}/templates/bump-repo.tmpl \
    -s namespace="${name}" \
    -s repobranch="${branch}" \
    -s repohttp="${http_repo}" \
    -s repossh="${ssh_repo}" \
    -o ${luet_dir}/bump-repo-${name}.yaml


  if [ "${upgrade_kit}" = "true" ] ; then
    echo "Creating upgrade kits task for repo ${name}..."
    kits2upgrade=$(yq r ${luet_values} "values.repositories[$i].kits2upgrade" -j  | jq '. | join(",")' -r)

    mottainai-cli task compile ${luet_dir}/templates/upgrade-kits.tmpl \
      -s namespace="${name}" \
      -s repobranch="${branch}" \
      -s repohttp="${http_repo}" \
      -s repossh="${ssh_repo}" \
      -s kits2upgrade="${kits2upgrade}" \
      -o ${luet_dir}/kits-upgrade/upgrade-kits-${name}.yaml

  fi
done

# vim: filetype=sh
