#!/bin/bash
# Description: Script to generate the tasks to build LXD images
# Author: Daniele Rondina, geaaru@funtoo.org

simplestreams_dir=$(dirname ${BASH_SOURCE[0]})/../simplestreams

TEMPLATE="${TEMPLATE:-${simplestreams_dir}/task.tmpl}"
IMAGES=$(yq r ${simplestreams_dir}/tree-images.yaml 'products' -l)

# LXD tasks
for ((i=0;i<$IMAGES;i++))
do
  product=$(yq r ${simplestreams_dir}/tree-images.yaml "products[$i].name")
  image_dir=$(yq r ${simplestreams_dir}/tree-images.yaml "products[$i].directory")
  planned=$(yq r ${simplestreams_dir}/tree-images.yaml "products[$i].planned")
  rt=$(yq r ${simplestreams_dir}/tree-images.yaml "products[$i].release_title")

  opts=""


  if [ ! -d ${simplestreams_dir}/${image_dir} ] ; then
    mkdir -p ${simplestreams_dir}/${image_dir}
  fi


  if [ -n "${planned}" ] ; then
    opts="-s planned=${planned}"
  fi

  echo "Creating task for image $rt..."
  mottainai-cli task compile ${TEMPLATE} ${opts} \
    -s product=${product} \
    -s image_dir=${image_dir} \
    -o ${simplestreams_dir}/${image_dir}/task.yaml

done

# vim: filetype=sh
