#!/bin/bash
# Description: Script to generate the tasks to build Macaroni ISOs.
# Author: Daniele Rondina, geaaru@funtoo.org

cdn_dir=$(dirname ${BASH_SOURCE[0]}})/../cdn

NS=$(yq r ${cdn_dir}/cdn-images.values 'values.namespaces' -l)

if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
  echo "Missing MOTTAINAI_CLI_PROFILE env variable"
  exit 1
fi

for ((i=0;i<$NS;i++))
do
  name=$(yq r ${cdn_dir}/cdn-images.values "values.namespaces[$i].name")
  namespace=$(yq r ${cdn_dir}/cdn-images.values "values.namespaces[$i].namespace")
  cdnstorage=$(yq r ${cdn_dir}/cdn-images.values "values.namespaces[$i].cdnstorage")

  opts=""
  if [ "${cdnstorage}" = "true" ] ; then
    echo "Creating task for sync namespace $namespace ($name)..."
    mottainai-cli task compile ${cdn_dir}/rsync-namespace.tmpl ${opts} \
      -s namespace="${namespace}" \
      -o ${cdn_dir}/rsync-${name}.yaml

    if [ -n "${FIRE_TASK}" ] ; then
      mottainai-cli task create --yaml ${cdn_dir}/rsync-${name}.yaml
    fi
  fi

  echo "Creating task for purge namespace $name..."
  mottainai-cli task compile ${cdn_dir}/purge-namespace.tmpl ${opts} \
    -s name="${name}" \
    -o ${cdn_dir}/purge/purge-${name}.yaml

done

# vim: filetype=sh
