#!/bin/bash
# Description: Script to generate the tasks to build Macaroni ISOs.
# Author: Daniele Rondina, geaaru@macaronios.org

cdn_dir=$(dirname ${BASH_SOURCE[0]}})/../cdn

NS=$(yq r ${cdn_dir}/cdn-images.values 'values.namespaces' -l)
#TEMPLATE=${TEMPLATE:-${cdn_dir}/rsync-namespace.tmpl}
TEMPLATE=${TEMPLATE:-${cdn_dir}/rsync-namespace-macaroni.tmpl}

if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
  echo "Missing MOTTAINAI_CLI_PROFILE env variable"
  exit 1
fi

for ((i=0;i<$NS;i++))
do
  name=$(yq r ${cdn_dir}/cdn-images.values "values.namespaces[$i].name")
  namespace=$(yq r ${cdn_dir}/cdn-images.values "values.namespaces[$i].namespace")

  echo "Creating task for purge namespace $name..."
  mottainai-cli task compile ${cdn_dir}/purge-namespace.tmpl ${opts} \
    -s name="${name}" \
    -o ${cdn_dir}/purge/purge-${name}.yaml

done

# vim: filetype=sh
