#!/bin/bash
# Description: Script to generate the tasks to build Macaroni ISOs.
# Author: Daniele Rondina, geaaru@funtoo.org

cdn_dir=$(dirname ${BASH_SOURCE[0]}})/../cdn

NS=$(yq r ${cdn_dir}/cdn-images.values 'values.namespaces' -l)

if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
  echo "Missing MOTTAINAI_CLI_PROFILE env variable"
  exit 1
fi

for ((i=0;i<$NS;i++))
do
  name=$(yq r ${cdn_dir}/cdn-images.values "values.namespaces[$i].name")

  opts=""
  echo "Creating task for sync namespace $name..."
  mottainai-cli task compile ${cdn_dir}/rsync-namespace.tmpl ${opts} \
    -s namespace="${name}" \
    -o ${cdn_dir}/rsync-${name}.yaml

  if [ -n "${FIRE_TASK}" ] ; then
    mottainai-cli task create --yaml ${cdn_dir}/rsync-${name}.yaml
  fi

done

# vim: filetype=sh
