#!/bin/bash
# Author: Daniele Rondina, geaaru@funtoo.org
# Description: Create task to execute luet-portage-converter for
#              a specific repository.

if [ -n "$DEBUG" ] ; then set -x ; fi

luet_dir=$(dirname ${BASH_SOURCE[0]}})/../luet
luet_values=${luet_dir}/luet-repo.values

main () {
  if [ -z "${NAMESPACE}" ] ; then
    echo "Missing NAMESPACE env variable."
    echo "Normally this variable is equal to repository name."
    return 1
  fi

  if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
    echo "Missing MOTTAINAI_CLI_PROFILE env variable."
    return 1
  fi

  local isvalid=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | length")
  if [ "${isvalid}" == "0" ] ; then
    echo "Selected repository not defined on luet-repo.values file."
    return 1
  fi

  local repo=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .http_repo" -r)
  local repo_branch=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .branch" -r)
  local repo_ssh=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .ssh_repo" -r)
  local upgrade_kit=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .upgrade_kit" -r)
  local kits2upgrade=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .kits2upgrade | join(\" \")" -r)
  local lpc_extra_ns=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .lpc_extra_ns | join(\",\")" -r)

  if [ "${upgrade_kit}" != "true" ] ; then
    echo "The selected repository is without upgrade_kit enable."
    return 1
  fi

  if [ "${kits2upgrade}" == "" ] ; then
    echo "The selected repository doesn't define kits2upgrade list on file ${luet_values}."
    return 1
  fi

  echo "
Kits 2 upgrade: ${kits2upgrade}
Extra Kits Namespace: ${lpc_extra_ns}
"

  rm -f /tmp/start-luet-pc.yaml || true

  local opts=""
  if [ -n "${lpc_extra_ns}" ] ; then
    opts="-s extrans=${lpc_extra_ns}"
  fi

  mottainai-cli task compile ${luet_dir}/templates/start-luet-pc.tmpl \
    -s namespace="${NAMESPACE}" ${opts} \
    -s repossh="${repo_ssh}" \
    -s repobranch="${repo_branch}" \
    -s kits2upgrade="${kits2upgrade}" \
    -o /tmp/start-luet-pc.yaml || return 1

  if [ "${FIRE_TASK}" = "1" ] ; then
    mottainai-cli task create --yaml /tmp/start-luet-pc.yaml || return 1
  fi

  return 0
}

main $@
exit $?

# vim: filetype=sh
