#!/bin/bash
# Description: Script to tag dev repo for testing.
# Author: Daniele Rondina, geaaru@funtoo.org

if [ -n "$DEBUG" ] ; then set -x ; fi

luet_dir=$(dirname ${BASH_SOURCE[0]}})/../luet
luet_values=${luet_dir}/luet-repo.values

FIRE_TASK=${FIRE_TASK:-0}

main () {

  if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
    echo "Missng MOTTAINAI_CLI_PROFILE env variable"
    exit 1
  fi

  if [ -z "${NAMESPACE}" ] ; then
    echo "Missing NAMESPACE env variable."
    echo "Normally this variable is equal to repository name."
    exit 1
  fi

  isvalid=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | length")
  if [ "${isvalid}" == "0" ] ; then
    echo "Selected repository not defined on luet-repo.values file."
    exit 1
  fi

  repo=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .http_repo" -r)
  repo_branch=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .branch" -r)
  repo4test=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .repo4test_tag" -r)
  tree_version=$(yq r ${luet_values} -j | jq ".values.repositories[] | select(.name==\"${NAMESPACE}\") | .tree_version" -r)


  if [ "${repo4test}" != "true" ] ; then
    echo "Selected repository invalid for tagging. See repo4test_tag field."
    exit 1
  fi

  echo "
Creating pipeline for tagging ${NAMESPACE}-dev to ${NAMESPACE}...
"

  mottainai-cli task compile ${luet_dir}/templates/move-dev2testing.tmpl \
    -s namespace="${NAMESPACE}" \
    -s repohttp="${repo}" \
    -s repobranch="${repo_branch}" \
    -s treeversion="${tree_version}" \
    -o /tmp/dev2test-pipeline.yaml || return 1

  if [ "${FIRE_TASK}" = "1" ] ; then
    mottainai-cli pipeline create --yaml /tmp/dev2test-pipeline.yaml || return 1
  fi

  return 0
}


main $@
exit $?

# vim: filetype=sh
